pid /tmp/my-music-nginx.pid;

events {
    worker_connections 1024;
}

http {
    include upstreams.conf;

    server {
        listen 8080;
        location /api/catalog/ {
            proxy_pass http://catalog;
        }
    }
}