upstream catalog {
    server 127.0.0.1:65535 down;
    server localhost:3000;
}
upstream playlist {
    server 127.0.0.1:65535 down;
    server localhost:3005;
    server localhost:3004;
}
upstream playback {
    server 127.0.0.1:65535 down;
    server localhost:3003;
    server localhost:3002;
}
upstream user {
    server 127.0.0.1:65535 down;
    server localhost:3007;
    server localhost:3006;
}
